// This file is auto-generated by @hey-api/openapi-ts

export const ActuatorEnumSchema = {
    type: 'string',
    enum: ['solenoid valve', 'proportional valve', 'pump'],
    title: 'ActuatorEnum',
    description: 'Enumeration for different types of actuators.'
} as const;

export const FlowmeterSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/SensorEnum',
            default: 'flowmeter'
        },
        id: {
            type: 'integer',
            minimum: 0,
            title: 'Id',
            examples: [0, 1, 2]
        },
        current_reading: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/SensorReading'
                },
                {
                    type: 'null'
                }
            ]
        },
        unit: {
            type: 'string',
            title: 'Unit',
            default: 'l/min'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'Flowmeter',
    description: 'Model for a flowmeter sensor.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ProportionalValveSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/ActuatorEnum',
            default: 'proportional valve'
        },
        id: {
            type: 'integer',
            minimum: -1,
            title: 'Id',
            examples: [0, 1, 2]
        },
        position: {
            type: 'integer',
            maximum: 100,
            minimum: 0,
            title: 'Position'
        }
    },
    type: 'object',
    required: ['id', 'position'],
    title: 'ProportionalValve',
    description: 'Model representing a proportional valve actuator.'
} as const;

export const PumpSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/ActuatorEnum',
            default: 'pump'
        },
        id: {
            type: 'integer',
            minimum: -1,
            title: 'Id',
            examples: [0, 1, 2]
        },
        running: {
            type: 'boolean',
            title: 'Running'
        }
    },
    type: 'object',
    required: ['id', 'running'],
    title: 'Pump',
    description: 'Model representing a pump actuator.'
} as const;

export const SensorEnumSchema = {
    type: 'string',
    enum: ['flowmeter'],
    const: 'flowmeter',
    title: 'SensorEnum',
    description: 'Enumeration for different types of sensors.'
} as const;

export const SensorReadingSchema = {
    properties: {
        value: {
            type: 'number',
            title: 'Value'
        },
        timestamp_ns: {
            type: 'integer',
            title: 'Timestamp Ns',
            description: 'Timestamp of the reading in nanoseconds since Epoch',
            examples: [1730906908814683100]
        }
    },
    type: 'object',
    required: ['value', 'timestamp_ns'],
    title: 'SensorReading',
    description: 'Base model for a sensor reading.'
} as const;

export const SolenoidValveSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/ActuatorEnum',
            default: 'solenoid valve'
        },
        id: {
            type: 'integer',
            minimum: -1,
            title: 'Id',
            examples: [0, 1, 2]
        },
        open: {
            type: 'boolean',
            title: 'Open'
        }
    },
    type: 'object',
    required: ['id', 'open'],
    title: 'SolenoidValve',
    description: 'Model representing a solenoid valve actuator.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;