// This file is auto-generated by @hey-api/openapi-ts

/**
 * Enumeration for different types of actuators.
 */
export enum ActuatorEnum {
    SOLENOID_VALVE = 'solenoid valve',
    PROPORTIONAL_VALVE = 'proportional valve',
    PUMP = 'pump'
}

/**
 * Model for a flowmeter sensor.
 */
export type Flowmeter = {
    type?: SensorEnum;
    id: number;
    current_reading?: (SensorReading | null);
    unit?: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Model representing a proportional valve actuator.
 */
export type ProportionalValve = {
    type?: ActuatorEnum;
    id: number;
    position: number;
};

/**
 * Model representing a pump actuator.
 */
export type Pump = {
    type?: ActuatorEnum;
    id: number;
    running: boolean;
};

/**
 * Enumeration for different types of sensors.
 */
export enum SensorEnum {
    FLOWMETER = 'flowmeter'
}

/**
 * Base model for a sensor reading.
 */
export type SensorReading = {
    value: number;
    /**
     * Timestamp of the reading in nanoseconds since Epoch
     */
    timestamp_ns: number;
};

/**
 * Model representing a solenoid valve actuator.
 */
export type SolenoidValve = {
    type?: ActuatorEnum;
    id: number;
    open: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetAllActuatorsV1ActuatorsGetResponse = (Array<(SolenoidValve | ProportionalValve | Pump)>);

export type GetAllActuatorsV1ActuatorsGetError = unknown;

export type GetAllV1ActuatorsSolenoidGetResponse = (Array<SolenoidValve>);

export type GetAllV1ActuatorsSolenoidGetError = unknown;

export type GetByIdV1ActuatorsSolenoidActuatorIdGetData = {
    path: {
        actuator_id: number;
    };
};

export type GetByIdV1ActuatorsSolenoidActuatorIdGetResponse = (SolenoidValve);

export type GetByIdV1ActuatorsSolenoidActuatorIdGetError = (HTTPValidationError);

export type SetStateV1ActuatorsSolenoidSetPostData = {
    body: SolenoidValve;
};

export type SetStateV1ActuatorsSolenoidSetPostResponse = (SolenoidValve);

export type SetStateV1ActuatorsSolenoidSetPostError = (HTTPValidationError);

export type GetAllV1ActuatorsProportionalGetResponse = (Array<ProportionalValve>);

export type GetAllV1ActuatorsProportionalGetError = unknown;

export type GetByIdV1ActuatorsProportionalActuatorIdGetData = {
    path: {
        actuator_id: number;
    };
};

export type GetByIdV1ActuatorsProportionalActuatorIdGetResponse = (ProportionalValve);

export type GetByIdV1ActuatorsProportionalActuatorIdGetError = (HTTPValidationError);

export type SetStateV1ActuatorsProportionalSetPostData = {
    body: ProportionalValve;
};

export type SetStateV1ActuatorsProportionalSetPostResponse = (ProportionalValve);

export type SetStateV1ActuatorsProportionalSetPostError = (HTTPValidationError);

export type GetAllV1ActuatorsPumpGetResponse = (Array<Pump>);

export type GetAllV1ActuatorsPumpGetError = unknown;

export type GetByIdV1ActuatorsPumpActuatorIdGetData = {
    path: {
        actuator_id: number;
    };
};

export type GetByIdV1ActuatorsPumpActuatorIdGetResponse = (Pump);

export type GetByIdV1ActuatorsPumpActuatorIdGetError = (HTTPValidationError);

export type SetStateV1ActuatorsPumpSetPostData = {
    body: Pump;
};

export type SetStateV1ActuatorsPumpSetPostResponse = (Pump);

export type SetStateV1ActuatorsPumpSetPostError = (HTTPValidationError);

export type GetAllSensorsV1SensorsGetResponse = (Array<Flowmeter>);

export type GetAllSensorsV1SensorsGetError = unknown;

export type GetAllV1SensorsFlowmetersGetResponse = (Array<Flowmeter>);

export type GetAllV1SensorsFlowmetersGetError = unknown;

export type GetByIdV1SensorsFlowmetersSensorIdGetData = {
    path: {
        sensor_id: number;
    };
};

export type GetByIdV1SensorsFlowmetersSensorIdGetResponse = (Flowmeter);

export type GetByIdV1SensorsFlowmetersSensorIdGetError = (HTTPValidationError);

export type PostReadingV1SensorsFlowmetersSensorIdReadingPostData = {
    body: SensorReading;
    path: {
        sensor_id: number;
    };
};

export type PostReadingV1SensorsFlowmetersSensorIdReadingPostResponse = (Flowmeter);

export type PostReadingV1SensorsFlowmetersSensorIdReadingPostError = (HTTPValidationError);

export type RootGetResponse = (unknown);

export type RootGetError = unknown;